Merge data from OpenAI with Wikipedia data

In [1]:
# Load wikipedia data
import pickle
with open("../wikipedia/selected_data.bin", "rb") as f:
    wikipedia = pickle.load(f)

In [2]:
wikipedia[0]

{'title': 'Creative computing',
 'text': 'Creative computing covers the interdisciplinary area at the cross-over of the creative arts and computing. Issues of creativity include knowledge discovery, for example.'}

In [3]:
# Load GPT data
import pandas as pd
df = pd.read_csv("./batchoutput.csv")

In [4]:
df.head()

                model                                               text
0  gpt-5.1-2025-11-13  Creative computing is the use of computer tech...
1  gpt-5.1-2025-11-13  Animal–computer interaction (ACI) is a researc...
2  gpt-5.1-2025-11-13  The frame problem is a foundational issue in a...
3  gpt-5.1-2025-11-13  KL-ONE is a classic knowledge representation s...
4  gpt-5.1-2025-11-13  Machine translation is the automatic conversio...

In [5]:
# Rename text to gpt_text
df.rename(columns={"text": "gpt_text"}, inplace=True)

In [6]:
df.head()

                model                                           gpt_text
0  gpt-5.1-2025-11-13  Creative computing is the use of computer tech...
1  gpt-5.1-2025-11-13  Animal–computer interaction (ACI) is a researc...
2  gpt-5.1-2025-11-13  The frame problem is a foundational issue in a...
3  gpt-5.1-2025-11-13  KL-ONE is a classic knowledge representation s...
4  gpt-5.1-2025-11-13  Machine translation is the automatic conversio...

In [7]:
# Collect title and human texts
titles = []
human_texts = []

for item in wikipedia:
    titles.append(item["title"])
    human_texts.append(item["text"])

In [8]:
# Insert data
df.insert(0, "title", titles)
df.insert(1, "human_text", human_texts)

In [9]:
df.head()

,title,human_text,model,gpt_text
0,Creative computing,Creative computing covers the interdisciplinar...,gpt-5.1-2025-11-13,Creative computing is the use of computer tech...
1,Animal-computer interaction,Animal-computer interaction (ACI) is a field o...,gpt-5.1-2025-11-13,Animal–computer interaction (ACI) is a researc...
2,Frame problem,"In artificial intelligence, the frame problem ...",gpt-5.1-2025-11-13,The frame problem is a foundational issue in a...
3,KL-ONE,KL-ONE is a well known knowledge representatio...,gpt-5.1-2025-11-13,KL-ONE is a classic knowledge representation s...
4,Machine translation,"Machine translation, sometimes referred to by ...",gpt-5.1-2025-11-13,Machine translation is the automatic conversio...

In [ ]:
df.to_csv("../../data/datasets/wikipedia_gpt.csv", index=False)